try:
    1/0
except Exception as err:
    print("The error is", str(err))

